name: pythia_cookbook_env
channels:
  - conda-forge
  - pyviz
dependencies:
  - jupyterhub-singleuser>=3.0
  - python
  - cartopy>=0.21.1
  - numpy<1.24.0
  - matplotlib
  - climlab
  - pandas
  - xarray
  - numba
  - dask
  - dask-gateway
  - tqdm
  - intake
  - intake-esm
  - fsspec
  - cftime
  - nc-time-axis
  - gcsfs
  - esgf-pyclient
  - jupyter=1.0.0
  - jupyterlab=3.5.2
  - pip:
    - setuptools==56.0.0
    - pyleoclim==0.11.0
    - pangaeapy
    - ipympl==0.9.2
    - folium