name: devtest
channels:
  - conda-forge
  - pyviz
dependencies:
  - jupyterlab
  - python
  - numpy<1.24.0
  - matplotlib
  - pandas
  - xarray
  - xesmf
  - xhistogram
  - numba
  - cartopy>=0.21.1
  - dask
  - dask-gateway
  - tqdm
  - intake
  - intake-esm
  - fsspec
  - cftime
  - nc-time-axis
  - gcsfs
  - s3fs
  - act-atmos
  - seaborn
  - esgf-pyclient
  - hvplot
  - holoviews