name: devtest
channels:
  - conda-forge
  - defaults
dependencies:
  # jupyterhub-singleuser version 3 or greater is a requirement for working well
  # with a JupyterHub such as at https://linkedearth.2i2c.cloud. After
  # https://github.com/jupyterhub/repo2docker/pull/1239 is merged, this doesn't
  # need to be specified.
  #
  - jupyterhub-singleuser>=3.0
  - cartopy>=0.21.1
  - pip
  - python=3.10
  - libstdcxx-ng=12.1.0
  - numpy<1.24.0
  - xarray=2023.2.0
  - pandas=2.0.0
  - intake=0.6.8
  - intake-esm=2022.9.18
  - netcdf4=1.6.2
  - aiohttp=3.8.4
  - zarr=2.14.2
  - s3fs=2023.3.0
  - fsspec=2023.3.0
  - requests=2.28.2
  - cftime=1.5.1.1
  - dask=2023.3.2
  - jupyter=1.0.0
  - jupyterlab=3.5.2
  - pip:
    - setuptools==56.0.0
    - pyleoclim
    - pangaeapy
    - nc-time-axis==1.4.1
    - ipympl==0.9.2
    - folium

