name: cmip6-cookbook-dev
channels:
  - conda-forge
  - pyviz
dependencies:
  - jupyterlab
  - python
  - numpy<1.24.0
  - matplotlib
  - pandas
  - xarray=2023.2.0
  - xesmf
  - numba
  - cartopy
  - dask
  - dask-gateway
  - tqdm
  - intake
  - intake-esm
  - fsspec
  - cftime
  - nc-time-axis
  - gcsfs
  - s3fs
  - seaborn
