name: devtest
channels:
  - conda-forge
  - defaults
dependencies:
  # jupyterhub-singleuser version 3 or greater is a requirement for working well
  # with a JupyterHub such as at https://linkedearth.2i2c.cloud. After
  # https://github.com/jupyterhub/repo2docker/pull/1239 is merged, this doesn't
  # need to be specified.
  #
  - jupyterhub-singleuser>=3.0
  - cartopy=0.21.1
  - pip
  - python=3.10
  - libstdcxx-ng=12.1.0
  - numpy=1.22.0
  - netcdf4=1.6.2
  - aiohttp=3.8.3
  - zarr=2.13.3
  - fsspec=2022.11.0
  - requests=2.28.2
  - xarray=2022.11.0
  - cftime=1.5.1.1
  - dask=2022.7.0
  - jupyter=1.0.0
  - jupyterlab_templates
  - pip:
    - setuptools==56.0.0
    - pyleoclim==0.10.0
    - nc-time-axis==1.4.1
    - ipympl==0.9.2

